apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: pythonapp
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: nwajienelson/pythonapp
        ports:
        - containerPort: 8500
        resources:
          requests:
            memory: "100Mi"
            cpu: "80m"
          limits:
            memory: "110Mi"
            cpu: "90m"
   







